### ISSUE TITLE
Show progress on installation

### ISSUE THREAD

**Issue by regg00** [regg00/ChocoMan#27]
**Is your feature request related to a problem? Please describe.**
Show some kind of progress on the installation of packages.

**Describe the solution you'd like**
Using `Write-Progress`, write the installation progress to the screen. Also, add a parameter to hide the progress. Refer to `ProgressPreference`.

**Describe alternatives you've considered**
Just showing the choco command output would do the trick, but it's not the PowerShell way.

**Comment by regg00** [comment]
@we-mi or @DailenG any interest and/or ideas on how to implement this?
I was thinking that running all install command in a PowerShell job and monitoring the download % and installation status would do the trick.

**Comment by regg00** [comment]
A simple spinner is actually a pretty good idea.
Like you said, it's not easy to predict/guess the percentage completed and I just want to show some kind of feedback while the process completes.

I just tested that snippet here locally and I think it would be enough.
https://gist.github.com/yoav-lavi/1253321d968db7f52d1a77ac48e3ff96

**Comment by we-mi** [comment]
Wow, I'd love to see this being implemented, but I think it might be very hard to reliably implement this. 

Although the majority of choco packages are installed "the classic way" (downloading a single file and installing this specific setup) there are a lot of packages which do things very differently.  
Just an example of packages I've stumbled across or created myself:
- The setup is included in the package itself (nothing is downloaded)
- Multiple files are downloaded and installed
- Nothing is downloaded or installed through `chocolateyInstall.ps1` (`.extension`-Packages are special types of packages which are extracted to a special chocolatey location without the need of a powershell install/uninstall/modify script or even a `tools`-folder.
- Packages whose only purpose it is to have dependencies to other packages. You are effectively installing multiple packages, although you only specified one package on the command line.

The problem is that you don't really know what a package does before you install it. Neither choco.exe knows this (except for calculating dependencies). It "just" executes a powershell script and this script can be 2 lines or 2000 lines.

My only guess for this feature would roughly look like this:
- start choco.exe with the dotNet object `System.Diagnostics.Process` (more powerful than `Start-Process` or `Start-Job`). I use this because the output of the command can be saved to variables instead of files (this is what `Start-Process` does) and you'll retrieve the output while choco is running and not just after it has finished.
- Waiting until choco.exe outputs how many packages are installed (it does this after the line `Installing the following packages:`)
- Build a list of expected steps/states. Then you know how many percent one step moves the progress bar forward
- Observe choco's output for every package which is going to be installed and search for your expected lines. I would suggest using only those lines which are displayed for every package. This could be:
  - Downloading the nupkg file (not the actual setup file)
  - Extraction of the nupkg (line: `<package> package files install completed. Performing other installation steps.`)
  - Finished installation (line: `The install of <package> was successful.`)

As a "bonus" you could display the last line of chocos output. This way the download progress of large setup files is displayed without the need to integrate this to your own percent calculation.

As you can see this can get out of hand quiet quickly and I don't know how future-proof and reliably this can be built. This could introduce more problems than it would solve (although it would be a very cool feature ;)).

Another thing to consider: I've observed that some packages start background processes which leads to the fact that the choco-process never really exits. You would need a timeout for the whole operation, but how long is long enough for large setups which takes some time?

A simple spinner looks fancy, but in my opinion it's not worth the effort. `Write-Progress` is the powershell-way for displaying progress-output and as long as this is displayed one can assume that the operation is still running. It's not giving much more information than a simple `Write-Progress` does.
This takes only two commands around the start of choco.exe, so it's also really easy to implement if you do not wish to implement the more complex way from above.

Maybe I'm trying to code something in the next days. I've built something similar for `restic` (a backup tool) but restic has the ability to continuously output json data with the current progress info which makes it WAY more easy to implement this)

And now it took me so long to write this, that you closed the issue in the meantime :D

**Comment by regg00** [comment]
Sorry about that @we-mi.
I just read the entire thing and I'll definitely give it a try locally.

You are right that a simple `Write-Progress` would be enough, but I think that the spinner increases the cool factor.

**Comment by we-mi** [comment]
Nothing to be sorry about :) It's your project.

And definitely true about the coolness ;)

**Comment by regg00** [comment]
I've played around with `Start-Job` and `System.Diagnostics.Process` and here's where I'm at.
I can't reliably parse the output since, for some reason, Start-Job and Process messes up the formatting which in return break most of the `-Match` I'm doing which in returns have some funny behavior.

e.g, I can find the string `package files install completed. Performing other installation steps.` as the end of a line with the `$` token, but since the formatting is messed up, on some package it works and on others it doesn't.

So for those reason, and the fact that I'm going on vacation, I'm calling the spinner "good enough".
