### ISSUE TITLE
Install-ChocoPackage: Name Parameter Supports String[] Value but does not Pass it to Choco

### ISSUE THREAD

**Issue by SirWobbyTheFirst** [regg00/ChocoMan#38]
**Describe the bug**
The Install-ChocoPackage Name parameter does support an array of package names being passed to it however it does not appear to invoke Chocolatey to install multiple packages. So if you run the following:

`$PackageList = @("conemu", "pwsh", "powertoys")`
`Install-ChocoPackage -Name $PackageList`

Only the first entry in the array (In this case ConEmu) will get installed. You can workaround the issue by using: 

`ForEach ($PackageName In $PackageList) { Install-ChocoPackage -Name $PackageName }`

However, that invokes Chocolatey each time.

**To Reproduce**
1. Define a string array with a list of Chocolatey package names such as `$PackageList = @("conemu", "pwsh", "powertoys")`
2. Pass the string array to the Name parameter for Install-ChocoPackage such as `Install-ChocoPackage -Name $PackageList`
3. Observe that only one package is installed in the output.
4. Call Get-ChocoPackage and observe that the two other packages in $PackageList are missing from the output.

**Expected behavior**
Passing a string[] value to the -Name parameter should install multiple packages defined in the array value.

**Desktop (please complete the following information):**
 - OS: Windows 11 (23H2)
 - ChocoMan Version: 1.2.3
 - PowerShell Version: 5.1 and 7.4.0

**Additional context**
Chocolatey does support passing a string array value to it directly as I've used this in the past on a virtual machine template to install multiple packages at the same time. The command to use is as simple as doing the following:

`$PackageList = @("conemu", "powertoys", "pwsh", "notepadplusplus")`
`choco install $PackageList -y`

**Comment by regg00** [comment]
Thanks for raising the issue.
I "fixed" it by removing the explicit `Return` statement in the `ForEach` block since it stopped the processing on the first element as you mentioned.

As for the passing of multiple packages on the same chocolatey command, I already played with it in the past, but the problem I had is with the processing of the output result.
Since chocolatey only returns plain-text, I can't reliably parse the output with regex when installing multiple packages at the same time, eg:
```
Installing the following packages:
vlc;terraform;speccy
By installing, you accept licenses for the packages.
vlc v3.0.20 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
terraform v1.6.5 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
speccy v1.32.803 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/3 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - speccy - speccy v1.32.803 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - terraform - terraform v1.6.5 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - vlc - vlc v3.0.20 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```

So, yeah, it's not the fastest when installing multiple packages, but I found that the overall stability is better that way.

@SirWobbyTheFirst, please take a look at [this branch](https://github.com/regg00/ChocoMan/tree/38-install-chocopackage-name-parameter-supports-string-value-but-does-not-pass-it-to-choco) for the fix and let me know what you think

**Comment by SirWobbyTheFirst** [comment]
Hi regg00,

Thanks for the quick response, yeah that looks good to me, as for the speed, that is perfectly fine. It helps me keep my deployment scripts cleaner, so again, thank you for the quick turnaround.

👍🏻
